version: '3.5'

services:
  rmqnamesrv:
    image: apacherocketmq/rocketmq:4.7.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmqs/logs:/opt/logs
      - ./rmqs/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms256M -Xmx256M -Xmn128m"
    command: ["sh","mqnamesrv"]

  rmqbroker0:
    image: apacherocketmq/rocketmq:4.7.0
    container_name: rmqbroker0
    ports:
      - 30911:30911
      - 40911:40911
    volumes:
      - ./rmq0/logs:/opt/logs
      - ./rmq0/store:/opt/store
      - ./dledger/broker-n0.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms256m -Xmx256m -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","106.52.208.123:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv

  rmqbroker1:
    image: apacherocketmq/rocketmq:4.7.0
    container_name: rmqbroker1
    ports:
      - 30921:30921
      - 40912:40912
    volumes:
      - ./rmq1/logs:/opt/logs
      - ./rmq1/store:/opt/store
      - ./dledger/broker-n1.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms256m -Xmx256m -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","106.52.208.123:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv

  rmqbroker2:
    image: apacherocketmq/rocketmq:4.7.0
    container_name: rmqbroker2
    ports:
      - 30931:30931
      - 40913:40913
    volumes:
      - ./rmq2/logs:/opt/logs
      - ./rmq2/store:/opt/store
      - ./dledger/broker-n2.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms256m -Xmx256m -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","106.52.208.123:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 80:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=106.52.208.123:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv